CREATE TABLE `t_user` (
 `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 `userId` VARCHAR ( 9 ) DEFAULT NULL COMMENT '用户ID',
 `userName` VARCHAR ( 16 ) DEFAULT NULL COMMENT '用户姓名',
 `mobileNo` VARCHAR ( 11 ) DEFAULT NULL COMMENT '手机号',
 `address` VARCHAR ( 100 ) DEFAULT NULL COMMENT '居住地址',
 `createTime` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
 `updateTime` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
 PRIMARY KEY ( `id` )
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='用户表';